services:
  t_base:
    container_name: t_base
    build: .
    ports:
      - 80:80
    command: bash -c "export FFREPORT=file=/app/ffreport.log:level=48 && cd tests && pytest -s"
    environment:
      APP_NAME: "t_base"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    env_file: .env_prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_TEST_DB},${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d

