services:
  t_base:
    container_name: t_base
    build: .
    ports:
      - 80:80
    command: bash -c "alembic upgrade head && gunicorn --workers=3 -b 0.0.0.0:80 -k uvicorn.workers.UvicornWorker main:app"
    environment:
      APP_NAME: "t_base"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "54320:5432"
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
    expose:
      - 6379
    command: redis-server
volumes:
  postgres_data: