"""info messages change

Revision ID: 27483580f233
Revises: 4cf2a551384a
Create Date: 2024-06-11 12:16:10.115176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27483580f233'
down_revision: Union[str, None] = '4cf2a551384a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('left_group_chat',
    sa.Column('leave_dates', postgresql.ARRAY(sa.DateTime()), server_default='{}', nullable=False),
    sa.Column('return_dates', postgresql.ARRAY(sa.DateTime()), server_default='{}', nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.add_column('messages', sa.Column('info_type', sa.String(length=50), nullable=True))
    op.add_column('messages', sa.Column('new_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('new_avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'new_avatar')
    op.drop_column('messages', 'new_name')
    op.drop_column('messages', 'info_type')
    op.drop_table('left_group_chat')
    # ### end Alembic commands ###
