"""last time edited and reply on delete

Revision ID: 2c6e7159fa81
Revises: 3e694d003492
Create Date: 2024-04-19 06:10:17.874711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6e7159fa81'
down_revision: Union[str, None] = '3e694d003492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('last_time_edited', sa.DateTime(), nullable=True))
    op.drop_constraint('messages_reply_on_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_on_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_reply_on_id_fkey', 'messages', 'messages', ['reply_on_id'], ['id'])
    op.drop_column('messages', 'last_time_edited')
    # ### end Alembic commands ###
