"""nullable text

Revision ID: 3e694d003492
Revises: c2c9bbbd6ead
Create Date: 2024-04-18 11:11:28.520810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e694d003492'
down_revision: Union[str, None] = 'c2c9bbbd6ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
