"""chat user relation fix

Revision ID: 4395f8c96a2b
Revises: 73ac795b91ff
Create Date: 2024-03-22 17:00:53.967835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4395f8c96a2b'
down_revision: Union[str, None] = '73ac795b91ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_users_association_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.message_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_users_association_table')
    # ### end Alembic commands ###
