"""deleted history fix2

Revision ID: 56538201ca11
Revises: fc92d75f6eb4
Create Date: 2024-05-16 06:52:24.254067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56538201ca11'
down_revision: Union[str, None] = 'fc92d75f6eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_history', sa.Column('date', sa.DateTime(), nullable=False))
    op.drop_column('deleted_history', 'deleted_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deleted_history', sa.Column('deleted_history', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('deleted_history', 'date')
    # ### end Alembic commands ###
