"""avatars and user description

Revision ID: 56a0b5dbe29e
Revises: 2c6e7159fa81
Create Date: 2024-04-20 07:39:51.756303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a0b5dbe29e'
down_revision: Union[str, None] = '2c6e7159fa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'description')
    op.drop_column('users', 'avatar')
    op.drop_column('chats', 'avatar')
    # ### end Alembic commands ###
