"""chat creator and name

Revision ID: 73ac795b91ff
Revises: 2e765ff4fc11
Create Date: 2024-03-22 16:20:14.340693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ac795b91ff'
down_revision: Union[str, None] = '2e765ff4fc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('name', sa.String(), nullable=False))
    op.add_column('chats', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'creator_id')
    op.drop_column('chats', 'name')
    # ### end Alembic commands ###
