"""message fix

Revision ID: 8079c3ff7f13
Revises: 444429ba2b0b
Create Date: 2024-04-11 05:49:44.289613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8079c3ff7f13'
down_revision: Union[str, None] = '444429ba2b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('photos', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.drop_column('messages', 'pictures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('pictures', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True))
    op.drop_column('messages', 'photos')
    # ### end Alembic commands ###
