"""reply on id fix

Revision ID: 8fbbdf54271c
Revises: 42f70613702e
Create Date: 2024-03-26 14:21:29.221860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbbdf54271c'
down_revision: Union[str, None] = '42f70613702e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'reply_on_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'reply_on_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
