"""ad history fix

Revision ID: f9584e840fad
Revises: 56538201ca11
Create Date: 2024-05-17 06:49:51.048116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ARRAY

# revision identifiers, used by Alembic.
revision: str = 'f9584e840fad'
down_revision: Union[str, None] = '56538201ca11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('added_deleted_user_history', 'deleted_dates')
    op.add_column('added_deleted_user_history', sa.Column('deleted_dates', ARRAY(sa.DateTime()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('added_deleted_user_history', 'deleted_dates',
               existing_type=postgresql.ARRAY(sa.DateTime()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###
